local bg = Def.ActorFrame{
	Def.ActorFrame{
		InitCommand=cmd(x,SCREEN_CENTER_X;y,SCREEN_CENTER_Y;diffusealpha,1;zoom,1);
		OnCommand=cmd(linear,0.25;diffusealpha,0);
		Def.Quad {
			InitCommand=cmd(Center;zoomto,SCREEN_WIDTH*500,SCREEN_HEIGHT*500;diffuse,Color("Black");linear,1;diffusealpha,1);
		};
		  Def.ActorFrame {
			  LoadActor(THEME:GetPathB("ScreenSelectMusic","overlay/out/fence")) .. {
				OnCommand=cmd(zoom,0.25;x,SCREEN_CENTER_X-440;y,SCREEN_CENTER_Y-240;diffusealpha,0.25);
			  };
		  };
	};
	LoadActor(THEME:GetPathS("","gameplay/Dark/in"))..{
		OnCommand=function(self)
			self:play();
		end;
	};
	--ARMY OF LIGHTS
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X);
			self:y(SCREEN_CENTER_Y);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X);
			self:y(SCREEN_CENTER_Y+300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X);
			self:y(SCREEN_CENTER_Y-300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-303);
			self:y(SCREEN_CENTER_Y);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+303);
			self:y(SCREEN_CENTER_Y);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-151.5);
			self:y(SCREEN_CENTER_Y+150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-455);
			self:y(SCREEN_CENTER_Y+150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+455);
			self:y(SCREEN_CENTER_Y+150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-455);
			self:y(SCREEN_CENTER_Y-150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+455);
			self:y(SCREEN_CENTER_Y-150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+151.5);
			self:y(SCREEN_CENTER_Y-150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-151.5);
			self:y(SCREEN_CENTER_Y-150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+151.5);
			self:y(SCREEN_CENTER_Y+150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-303);
			self:y(SCREEN_CENTER_Y-300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+303);
			self:y(SCREEN_CENTER_Y+300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-303);
			self:y(SCREEN_CENTER_Y+300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+303);
			self:y(SCREEN_CENTER_Y-300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/shiny"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	--ARMY OF FRAMES
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X);
			self:y(SCREEN_CENTER_Y);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X);
			self:y(SCREEN_CENTER_Y+300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X);
			self:y(SCREEN_CENTER_Y-300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-303);
			self:y(SCREEN_CENTER_Y);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+303);
			self:y(SCREEN_CENTER_Y);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-151.5);
			self:y(SCREEN_CENTER_Y+150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-455);
			self:y(SCREEN_CENTER_Y+150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+455);
			self:y(SCREEN_CENTER_Y+150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-455);
			self:y(SCREEN_CENTER_Y-150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+455);
			self:y(SCREEN_CENTER_Y-150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+151.5);
			self:y(SCREEN_CENTER_Y-150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-151.5);
			self:y(SCREEN_CENTER_Y-150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+151.5);
			self:y(SCREEN_CENTER_Y+150);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-303);
			self:y(SCREEN_CENTER_Y-300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+303);
			self:y(SCREEN_CENTER_Y+300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X-303);
			self:y(SCREEN_CENTER_Y+300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	Def.Sprite{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X+303);
			self:y(SCREEN_CENTER_Y-300);
			self:zoom(0.3);
		end;
		StartTransitioningCommand = function(self)
				self:Load(THEME:GetPathB("ScreenWithMenuElements","out/square"));
				self:decelerate(0.25);
				self:zoom(0);
		end;
	};
	LoadActor(THEME:GetPathB("ScreenWithMenuElements","background/dark/emblem"))..{
		InitCommand=function(self)
			self:x(SCREEN_CENTER_X);
			self:y(SCREEN_CENTER_Y);
			self:diffusealpha(1);
			self:zoom(0.15);
		end;
		StartTransitioningCommand = function(self)
			self:decelerate(0.25);
			self:zoom(1);
			self:diffusealpha(0);
		end;
	};
};

return bg